### ISSUE TITLE
How to Run  Chat Demo Server on my localhost?

### ISSUE THREAD

**Issue by gam6itko** [ratchetphp/socketo.me#20]
help me

**Comment by cboden** [comment]
* Install the composer dependencies
* Run `make` (or the commands under build in Makefile)
* cd bin
* Create a config.php file, inside file set `$host = 'localhost';`
* Run php run-all-the-things.php

**Comment by gam6itko** [comment]
Where I can find `.htaccess.example` file ?

**Comment by cboden** [comment]
I run socketo.me on Nginx, not Apache so there is no `.htacceess` file. If you have vagrant you can get a guest environment set up easily.

**Comment by gam6itko** [comment]
Vagrant box ` https://github.com/downloads/roderik/VagrantQuantal64Box/quantal64.box` is not find

**Comment by cboden** [comment]
Hmm, I guess that box is no longer available...You could look for a quantal64 box on https://vagrantcloud.com and replace it in the `Vagrantfile`
