### ISSUE TITLE
Demo folder missing

### ISSUE THREAD

**Issue by rhmoult** [ratchetphp/socketo.me#25]
Chris, I'm a big fan of RatchetPHP, and would like to extend your demo app.  I cannot get it working, however.

I have set up an Ubuntu server with nginx, installed php-fpm and php-cli, cloned your git repo, and ran composer.phar install.  localhost/socketo.me/web/index.php works fine, but the demo link takes me to /demo, which doesn't exist on the filesystem.

I'd much appreciate any insight you can provide.  

-Rich

**Comment by rhmoult** [comment]
I should mention that php bin/run-all-the-things.php results in a blank page when I visit.

**Comment by cboden** [comment]
Make sure you have all files go through index.php in your nginx config, [like this](https://github.com/ratchetphp/socketo.me/blob/master/vagrant/templates/nginx-localhost.conf#L12). The website is a Silex app and /demo is dynamically generated. 

Your browser doesn't visit bin/run-all-the-things.php you have to run that from your CLI.

**Comment by rhmoult** [comment]
That was a big help.  Thanks!  My next issue is that when the demo starts up, I am in offline mode and unable to chat.  I am going to spend the next 9 hours on getting a good understanding of the existing codebase, but I'd much appreciate any thoughts you have on where I should look to resolve this issue.

**Comment by rhmoult** [comment]
After checking out your youtube video presentation to Ski PHP, I see that the issue was my call to open the server did not include '0.0.0.0'.  You answer this question in about 45 seconds at https://youtu.be/04jVCKLXttk?t=1020

Thanks again!

**Comment by cboden** [comment]
Awesome! :+1:
