### ISSUE TITLE
Wait for client side to respond within given timeout

### ISSUE THREAD

**Issue by sajawalsz** [ratchetphp/socketo.me#31]
In the onmessage of MessageComponentInterface I can't find a way to wait for client side to respond within given time stamp just to check the connectivity plus provide client side a grace period even if it has disconnected it can respond back in given time.  
This is what i'm trying to achieve

             foreach ($this->clients as $client) {
                if(in_array($client->resourceId, $resourcearrays)){
                    $client->send('wait_for_message');
                    $reply = $client->wait_for_reply(15); //something like this of 15 seconds
                    if($reply == 200){
                   //do nothing 
                   }else{
                   //kick him out of my array $resourcearrays.
                   }
                }
            }

Help me out please.

**Comment by mbonneau** [comment]
Closed for inactivity.
