### ISSUE TITLE
Potential mistake in the "Push Integration" tutorial - PHP Fatal error: Uncaught Error: Class "MyApp\Pusher" not found

### ISSUE THREAD

**Issue by hayden-t** [ratchetphp/socketo.me#52]
Hi, guys ! I just kept getting stuck with: http://socketo.me/docs/push

PHP Fatal error:  Uncaught Error: Class "MyApp\Pusher" not found in /home/xxx/src/MyApp/Server.php:5

Im new to this, but it seems the mistake is asking to save the Pusher class in MyApp folder: 
`Save this in /src/MyApp/Pusher.php`
when with the following psr you wont find it 
` "MyApp\\": "src"`
to compare in the hello world example you save the scripts in the src folder:

`Save this as /src/Chat.php. We'll come back to our Chat class soon.`

yet it uses the same psr spec:
"MyApp\\": "src"

By changing to:
`"MyApp\\": "src/MyApp"`

The error goes away and it works... hard to believe this hasnt been pickup up before, such that ive spent 2 hours thinking it was my fault....

**Comment by SimonFrings** [comment]
Thank you for bringing this up. I have transferred this issue to https://github.com/ratchetphp/socketo.me, as it addresses a problem with the documentation.

I agree with you that the documentation is currently inconsistent. It should either say, "Save this in /src/Pusher.php," or change the PSR spec to `"MyApp": "src/MyApp"`, as you suggested above. I am unsure if it's necessary to create a `MyApp` directory inside `src`, so I personally would go with my first option and change the sentence in the documentation.

Would you be interested in looking into this and filing a pull request to fix the issue?

**Comment by hayden-t** [comment]
https://github.com/ratchetphp/socketo.me/pull/53
