### ISSUE TITLE
Accessing website currently results in `502 Bad Gateway` response

### ISSUE THREAD

**Issue by SimonFrings** [ratchetphp/socketo.me#54]
When trying to access the Ratchet website (http://socketo.me/) you'll currently get a `502 Bad Gateway` response. This issue seems to be similar to #46, this needs some further investigation.

![grafik](https://github.com/ratchetphp/socketo.me/assets/44357440/28b03dea-144a-4ac0-801e-ca9c16d24d19)

If you need to access the documentation you can still use [the Wayback machine](https://web.archive.org/web/20220224103313/http://socketo.me/docs/) as suggested in https://github.com/ratchetphp/socketo.me/issues/46#issuecomment-1169171068 until this problem is resolved.

**Comment by cboden** [comment]
Rebooted the server, fixed now
